catch more errors and delete on rerun

diff --git a/install-proc b/install-proc
--- a/install-proc
+++ b/install-proc
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+set -e
+
 if [[ $EUID -eq 0 ]]; then
 echo "   ##############################################"
 echo "  # IT IS NOT A GOOD IDEA TO RUN THIS AS ROOT! #"
@@ -9,16 +11,25 @@ exit 1
 fi
 
 
+if [[ -d "libusb-1.0.18" ]] || [[ -d "libftdi1-1.1" ]] || [[ -d "libpinproc" ]] || [[ -d "pypinproc" ]]
+then
+    echo "[CLEANUP] Will cleanup first"
+    echo "Directories already exist. Do you want to delete them? Enter YES to proceed."
+    read should_delete
+    if ( "$year" != "YES" )
+    then
+        echo "CANNOT PROCEED"
+        exit 1
+    fi
+
+    sudo rm -R libusb-1.0.18 libftdi1-1.1 libpinproc pypinproc || true
+fi
+
 ##########################################
 ##         P-ROC and P3 Support         ##
 ##########################################
 echo "[PROC PREREQS] Installing PROC prerequisites via apt-get"
 sudo apt-get -y install cmake gcc g++ build-essential git-core zlib1g-dev libudev-dev libusb-dev pkg-config libboost-dev
-
-if [ $? -ne 0 ]; then
-echo "apt failed."
-exit 1
-fi
 
 echo "[LIBUSB1] Installing libusb1"
 
@@ -27,11 +38,6 @@ cd libusb-1.0.18
 ./configure
 make
 sudo make install
-
-if [ $? -ne 0 ]; then
-echo "libusb1 install failed."
-exit 1
-fi
 
 echo "Backing out to main directory..."
 
@@ -45,11 +51,6 @@ cd libusbx-1.0.18
 make
 sudo make install
 
-if [ $? -ne 0 ]; then
-echo "libusbx install failed."
-exit 1
-fi
-
 echo "Backing out to main directory..."
 
 cd ../
@@ -58,54 +59,22 @@ echo "[LIBFTDI1] Installing libftdi1"
 
 tar -jxpvf libftdi1-1.1.tar.bz2
 cd libftdi1-1.1
-mkdir bin
+mkdir -p bin
 cd bin
 cmake ..
 make
 sudo make install
 
-if [ $? -ne 0 ]; then
-echo "LIBFTDI1 install failed."
-exit 1
-fi
-
 echo "Backing out to main directory..."
 cd ../..
-
-#echo "[YAML-CPP] Installing YAML-CPP"
-
-#tar -zxpvf yaml-cpp-0.2.5.tar.gz
-#cd yaml-cpp-0.2.5/
-#mkdir bin
-#cd bin
-#cmake ..
-#make
-#sudo make install
-
-#if [ $? -ne 0 ]; then
-#echo "YAML-CPP install failed."
-#exit 1
-#fi
-
-#echo "Backing out to main directory..."
-#cd ../..
 
 echo "Setting up environment variables..."
 
 export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
-export C_INCLUDE_PATH_TEMP=$(find /usr/ -name ftdi.h -printf '%h\072')
-export CPLUS_INCLUDE_PATH_TEMP=$(find /usr/ -name ftdi.h -printf '%h\072')
 export C_INCLUDE_PATH=$(find /usr/ -name ftdi.h -printf '%h\072')
 export CPLUS_INCLUDE_PATH=$(find /usr/ -name ftdi.h -printf '%h\072')
 
-
 echo "Stuff should be exported now"
-
-echo "export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH" >> ~/.bashrc
-echo "export C_INCLUDE_PATH="$C_INCLUDE_PATH_TEMP":$C_INCLUDE_PATH" >> ~/.bashrc
-echo "export CPLUS_INCLUDE_PATH="$CPLUS_INCLUDE_PATH_TEMP":$CPLUS_INCLUDE_PATH" >> ~/.bashrc
-
-source ~/.bashrc
 
 sudo cp 50-P-ROC.rules /etc/udev/rules.d
 sudo cp 51-P3-ROC.rules /etc/udev/rules.d
@@ -117,17 +86,12 @@ echo "[LIBPINPROC] Installing libpinproc"
 git clone --branch dev https://github.com/missionpinball/libpinproc.git libpinproc
 cd libpinproc
 
-mkdir bin
+mkdir -p bin
 cd bin
 
 cmake -DBUILD_SHARED_LIBS=ON ..
 make
 sudo make install
-
-if [ $? -ne 0 ]; then
-echo "libpinproc installation failed."
-exit 1
-fi
 
 echo "Backing out to main directory..."
 
@@ -139,11 +103,6 @@ git clone https://github.com/missionpinball/pypinproc pypinproc
 cd pypinproc
 sudo python3 setup.py install
 
-if [ $? -ne 0 ]; then
-echo "PyPinproc installation failed"
-exit 1
-fi
-
 echo "Backing out to main directory..."
 
 
@@ -154,7 +113,7 @@ echo "     (It's complicated, but then again, so is pinball.)"
 echo ""
 
 echo "      When you are done, you'll need to install MPF. The"
-echo "       quick way is to simply run: 'pip3 install mpf-mc'"
+echo "       quick way is to use the MPF debian installer "
 echo "        after you reboot. More information is available"
 echo "                  at docs.missionpinball.org"
 echo ""
